version: '3.8'

services:
  frontend:
    container_name: trivia-frontend 
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:8081"
    networks:
      - web
  backend:
    container_name: trivia-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - web

networks:
  web:
    external: true