version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:80"


  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}