FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
COPY tsconfig*.json ./
COPY src/controller ./src/controller
COPY src/types ./src/types
RUN npm install

EXPOSE 3000
CMD ["npm", "run", "dev-backend"]