FROM node:20-alpine

WORKDIR /app
COPY ./frontend/package*.json ./
COPY ./frontend/tsconfig*.json ./
COPY tsconfig*.json ./
COPY ./frontend/vite.config.ts ./
COPY ./frontend/src ./src
COPY ./frontend/index.html ./

RUN npm install
RUN npm run build

# Add a simple static file server
RUN npm install -g serve
EXPOSE 8081
CMD ["serve", "-s", "dist", "-l", "8081"]